import { chromium } from 'playwright'
const PORT = process.env.PORT || 4930
const b = await chromium.launch()
const p = await b.newPage({ viewport:{width:390,height:844}, deviceScaleFactor:2, isMobile:true, hasTouch:true })
const errs=[]; p.on('pageerror',e=>errs.push(e.message))
await p.goto(`http://localhost:${PORT}/seasons/?dev=1`,{waitUntil:'domcontentloaded',timeout:60000})
await p.locator('.gate').click().catch(()=>{}); await p.waitForTimeout(1500)
await p.evaluate(()=>window.__applyScene('kitaterao-window-3d')).catch(()=>{}); await p.waitForTimeout(3500)
const attr = await p.evaluate(()=>window.__town3dAttribute && window.__town3dAttribute())
const histo = await p.evaluate(()=>window.__town3dMeshHisto && window.__town3dMeshHisto())
console.log('=== window view draw-call attribution ===')
console.log(JSON.stringify(attr))
console.log('=== mesh histogram ===')
console.log(JSON.stringify(histo))
console.log(errs.length?('ERR '+errs.slice(0,2).join(' | ')):'no err')
await b.close()
