import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
const errs = []
page.on('pageerror', (e) => errs.push('PE:' + e.message))
page.on('console', (m) => { if (m.type() === 'error') errs.push('CE:' + m.text()) })
await page.goto('http://localhost:4875/seasons/?dev=1', { waitUntil: 'networkidle' })
await page.locator('.gate').click().catch(() => {})
await page.waitForTimeout(500)
await page.addStyleTag({ content: '.ui{display:none !important}' })
await page.evaluate(() => window.__applyScene && window.__applyScene('autumn-dusk-corner-room'))
await page.waitForTimeout(3200)
const hasStage = await page.evaluate(() => !!document.querySelector('.town3d-stage'))
await page.screenshot({ path: 'scripts/_shots/qa-corner1.png' })
console.log('town3d-stage生成:', hasStage, '/', errs.length ? 'エラー:' + JSON.stringify(errs.slice(0,4)) : 'エラー無し')
await browser.close()
