import { chromium } from 'playwright'
const port = process.env.PORT || '4801'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 900, height: 600 }, deviceScaleFactor: 1.8 })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
await p.goto(`http://localhost:${port}/seasons/?dev=1`, { waitUntil: 'networkidle' })
await p.locator('.gate').click().catch(()=>{})
await p.waitForTimeout(700)
await p.evaluate(()=>window.__applyScene('summer-morning-corner-room')); await p.waitForTimeout(2800)
await p.screenshot({ path:'scripts/_shots/corner-center.png' })
await p.evaluate(()=>{ for(let i=0;i<12;i++) window.__town3dLook(30,0) }); await p.waitForTimeout(800)
await p.screenshot({ path:'scripts/_shots/corner-right.png' })
await p.evaluate(()=>{ for(let i=0;i<24;i++) window.__town3dLook(-30,0) }); await p.waitForTimeout(800)
await p.screenshot({ path:'scripts/_shots/corner-left.png' })
console.log(errs.length?'ERR '+errs.slice(0,2):'no errors')
await b.close()
