import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
page.on('pageerror', e => console.log('ERR', e.message))
await page.goto('http://localhost:4801/seasons-gpu/?dev=1', { waitUntil: 'networkidle' })
await page.locator('.gate').click().catch(()=>{})
await page.waitForTimeout(600)
await page.addStyleTag({ content: '.ui{display:none !important}' })
await page.evaluate(()=>window.__applyScene('kitaterao-window-3d'))
await page.waitForTimeout(1800)
await page.evaluate(()=>window.__town3dWindow(true)); await page.waitForTimeout(900)
await page.evaluate(()=>window.__town3dLean(true)); await page.waitForTimeout(1100)
await page.evaluate(()=>window.__town3dFly(true)); await page.waitForTimeout(300)
// 祭りの屋台の湯気（公園を斜め上から）
await page.evaluate(()=>{ window.__town3dCruise(false); window.__town3dZoom(1.0); window.__town3dFlyPose(24, 13, -12, -0.95, -0.42) })
await page.waitForTimeout(1200)
await page.screenshot({ path: 'scripts/_shots/steam.png' })
// 観覧車の乗客
await page.evaluate(()=>{ window.__town3dZoom(0.8); window.__town3dFlyPose(-26, 16, -52, 0, -0.05) })
await page.waitForTimeout(700)
await page.screenshot({ path: 'scripts/_shots/rider.png' })
await browser.close()
