import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
const errs = []
page.on('pageerror', (e) => errs.push('PE:' + e.message))
page.on('console', (m) => { if (m.type() === 'error') errs.push('CE:' + m.text()) })
await page.goto('http://localhost:4875/seasons/?dev=1', { waitUntil: 'networkidle' })
await page.locator('.gate').click().catch(() => {})
await page.waitForTimeout(500)
await page.addStyleTag({ content: '.ui{display:none !important}' })
await page.evaluate(() => window.__applyScene && window.__applyScene('summer-dusk-downtown'))
await page.waitForTimeout(2200)
await page.evaluate(() => window.__driftTo && window.__driftTo(0.45)); await page.waitForTimeout(700)
await page.screenshot({ path: 'scripts/_shots/qa-drift-open.png' })
await page.evaluate(() => window.__driftTo && window.__driftTo(1.0)); await page.waitForTimeout(700)
await page.screenshot({ path: 'scripts/_shots/qa-drift-late.png' })
console.log(errs.length ? 'エラー: ' + JSON.stringify(errs.slice(0,6)) : 'エラー無し')
await browser.close()
