import { chromium } from 'playwright'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 900, height: 560 }, deviceScaleFactor: 2 })
const errs = []
p.on('pageerror', (e) => errs.push(String(e)))
p.on('console', (m) => { if (m.type()==='error') errs.push(m.text()) })
await p.goto('http://localhost:4801/seasons/?dev=1', { waitUntil: 'networkidle' })
await p.locator('.gate').click().catch(()=>{})
await p.waitForTimeout(700)
await p.evaluate(()=>window.__applyScene('kitaterao-window-3d'))
await p.waitForTimeout(2400)
await p.evaluate(()=>window.__town3dFly(true)); await p.waitForTimeout(700)
await p.evaluate(()=>window.__town3dCruise(false))
// 江戸(640,-46) を望む
await p.evaluate(()=>window.__town3dFlyPose(560, 50, -46, Math.PI/2, -0.12)); await p.waitForTimeout(1400)
await p.screenshot({ path: 'scripts/_shots/era-edo.png' })
// 戦国(140,-640)
await p.evaluate(()=>window.__town3dFlyPose(140, 48, -560, 0, -0.12)); await p.waitForTimeout(1400)
await p.screenshot({ path: 'scripts/_shots/era-sengoku.png' })
// 大正(-640,-30)
await p.evaluate(()=>window.__town3dFlyPose(-560, 50, -30, -Math.PI/2, -0.12)); await p.waitForTimeout(1400)
await p.screenshot({ path: 'scripts/_shots/era-taisho.png' })
console.log(errs.length ? 'ERR '+errs.slice(0,4).join(' | ') : 'no errors')
await b.close()
