import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
page.on('pageerror', e => console.log('PAGE ERROR', e.message))
await page.goto('http://localhost:4801/seasons/?dev=1', { waitUntil: 'networkidle' })
await page.locator('.gate').click().catch(()=>{})
await page.waitForTimeout(600)
await page.addStyleTag({ content: '.ui{display:none !important}' })
await page.evaluate(()=>window.__applyScene('kitaterao-window-3d'))
await page.waitForTimeout(1800)
await page.evaluate(()=>window.__town3dWindow(true)); await page.waitForTimeout(900)
await page.evaluate(()=>window.__town3dLean(true)); await page.waitForTimeout(1100)
await page.evaluate(()=>window.__town3dFly(true)); await page.waitForTimeout(300)
// 高空俯瞰
await page.evaluate(()=>{ window.__town3dCruise(false); window.__town3dZoom(1.5); window.__town3dFlyPose(10, 64, -8, 0, -0.5) })
await page.waitForTimeout(800)
await page.screenshot({ path: 'scripts/_shots/final-fly.png' })
// 着地して歩く（公園へ）
await page.evaluate(()=>window.__town3dFlyPose(16, 9, -12, 0, -0.2)); await page.waitForTimeout(500)
await page.evaluate(()=>window.__town3dLand(true)); await page.waitForTimeout(1500)
await page.evaluate(()=>window.__town3dMove(0,1)); await page.waitForTimeout(900)
await page.evaluate(()=>window.__town3dMove(0,0))
await page.screenshot({ path: 'scripts/_shots/final-walk.png' })
const dbg = await page.evaluate(()=>window.__town3dDbg && window.__town3dDbg())
console.log('歩行:', JSON.stringify(dbg))
await browser.close()
