import { chromium } from 'playwright'
const PORT = process.env.PORT || 4876
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 760, height: 680 } })
await page.goto(`http://localhost:${PORT}/seasons/?dev=1`, { waitUntil: 'networkidle' })
await page.locator('.gate').click().catch(() => {})
await page.waitForTimeout(800)
await page.evaluate(() => window.__applyScene && window.__applyScene('summer-dusk-downtown')).catch(() => {})
await page.waitForTimeout(3000)
console.log('fns:', await page.evaluate(() => ['__town3dFly','__town3dFlyPose','__town3dDbg','__town3dLand'].map(n=>n+':'+(typeof window[n]))))
console.log('dbg pre:', JSON.stringify(await page.evaluate(() => window.__town3dDbg && window.__town3dDbg())))
await page.evaluate(() => window.__town3dFly && window.__town3dFly(true))
await page.waitForTimeout(1500)
console.log('dbg fly:', JSON.stringify(await page.evaluate(() => window.__town3dDbg && window.__town3dDbg())))
await page.evaluate(() => window.__town3dFlyPose && window.__town3dFlyPose(0, 8, -10, 0, -0.3))
await page.waitForTimeout(1500)
console.log('dbg pose:', JSON.stringify(await page.evaluate(() => window.__town3dDbg && window.__town3dDbg())))
await browser.close()
