import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
const errs = []
page.on('pageerror', (e) => errs.push(e.message))
await page.goto('http://localhost:4875/seasons-gpu/?dev=1', { waitUntil: 'networkidle' })
await page.locator('.gate').click().catch(() => {})
await page.waitForTimeout(500)
await page.addStyleTag({ content: '.ui{display:none !important}' })
await page.evaluate(() => window.__applyScene && window.__applyScene('kitaterao-window-3d'))
await page.waitForTimeout(2800)
await page.screenshot({ path: 'scripts/_shots/qa-grid-front.png' })
await page.evaluate(() => window.__town3dLean && window.__town3dLean(true))
await page.waitForTimeout(5000)
await page.evaluate(() => window.__town3dSetView && window.__town3dSetView(0.2, 0.2))
await page.waitForTimeout(900)
await page.screenshot({ path: 'scripts/_shots/qa-grid-look.png' })
console.log(errs.length ? 'エラー: ' + JSON.stringify(errs.slice(0,4)) : 'エラー無し')
await browser.close()
