import { chromium } from 'playwright'
const port = process.env.PORT || '4801'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 900, height: 600 }, deviceScaleFactor: 1.5 })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
await p.goto(`http://localhost:${port}/seasons-gpu/?dev=1`, { waitUntil: 'networkidle' })
await p.locator('.gate').click().catch(()=>{})
await p.waitForTimeout(800)
await p.evaluate(()=>window.__applyScene('kitaterao-window-3d-sunset'))
await p.waitForTimeout(2600)
// 飛んで→着地して歩行モードへ
await p.evaluate(()=>window.__town3dFly(true)); await p.waitForTimeout(700)
await p.evaluate(()=>window.__town3dFlyPose(0,16,-30,0,-0.1)); await p.waitForTimeout(600)
await p.evaluate(()=>window.__town3dLand&&window.__town3dLand(true)); await p.waitForTimeout(4000)
console.log('walk state:', JSON.stringify(await p.evaluate(()=>window.__town3dJumpState())))
await p.evaluate(()=>window.__town3dJump()); await p.waitForTimeout(180)
console.log('mid-jump:', JSON.stringify(await p.evaluate(()=>window.__town3dJumpState())))
await p.waitForTimeout(700)
console.log('after-land:', JSON.stringify(await p.evaluate(()=>window.__town3dJumpState())))
console.log(errs.length?'ERR '+errs.slice(0,2):'no errors')
await b.close()
