import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
page.on('pageerror', e => console.log('ERR', e.message))
await page.goto('http://localhost:4801/seasons-gpu/?dev=1', { waitUntil: 'networkidle' })
await page.locator('.gate').click().catch(()=>{})
await page.waitForTimeout(600)
await page.addStyleTag({ content: '.ui{display:none !important}' })
await page.evaluate(()=>window.__applyScene('kitaterao-window-3d-spring'))
await page.waitForTimeout(2400)
await page.evaluate(()=>window.__town3dWindow(true)); await page.waitForTimeout(900)
await page.evaluate(()=>window.__town3dLean(true)); await page.waitForTimeout(1100)
await page.evaluate(()=>window.__town3dFly(true)); await page.waitForTimeout(300)
await page.evaluate(()=>{ window.__town3dCruise(false); window.__town3dZoom(1.1); window.__town3dFlyPose(-12, 14, -28, 0, -0.25) })
await page.waitForTimeout(800)
await page.screenshot({ path: 'scripts/_shots/koi-0.png' })
await page.evaluate(()=>{ window.__town3dZoom(0.9); window.__town3dFlyPose(-44, 11, -14, 0, -0.12) })
await page.waitForTimeout(800)
await page.screenshot({ path: 'scripts/_shots/koi-1.png' })
await browser.close()
