import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
page.on('pageerror', e => console.log('ERR', e.message))
await page.goto('http://localhost:4801/seasons-gpu/?dev=1', { waitUntil: 'networkidle' })
await page.locator('.gate').click().catch(()=>{})
await page.waitForTimeout(600)
await page.addStyleTag({ content: '.ui{display:none !important}' })
await page.evaluate(()=>window.__applyScene('kitaterao-window-3d-night'))
await page.waitForTimeout(2400)
await page.evaluate(()=>window.__town3dWindow(true)); await page.waitForTimeout(900)
await page.evaluate(()=>window.__town3dLean(true)); await page.waitForTimeout(1100)
await page.evaluate(()=>window.__town3dFly(true)); await page.waitForTimeout(300)
await page.evaluate(()=>{ window.__town3dCruise(false); window.__town3dZoom(1.1); window.__town3dFlyPose(-26, 12, -50, 0, -0.18) })
await page.waitForTimeout(700)
await page.screenshot({ path: 'scripts/_shots/merge-ferris.png' })
await page.evaluate(()=>{ window.__town3dZoom(1.0); window.__town3dFlyPose(0, 8, -6, 0, -0.2) })
await page.waitForTimeout(700)
await page.screenshot({ path: 'scripts/_shots/merge-shoten.png' })
await browser.close()
