import { chromium } from "playwright"
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 480, height: 880 }, deviceScaleFactor: 2 })
await p.goto("http://localhost:4801/seasons-gpu/?dev=1", { waitUntil: "networkidle" })
await p.locator(".gate").click().catch(() => {})
await p.waitForTimeout(700)
await p.evaluate(() => window.__applyScene("kitaterao-window-3d"))
await p.waitForTimeout(2500)
await p.evaluate(() => window.__town3dFly(true))
await p.waitForTimeout(2500)
await p.evaluate(() => window.__town3dCruise(false))
await p.waitForTimeout(2200)
const hover = await p.evaluate(() => ({ pr: window.__town3dStats().pr, vel: window.__town3dDbg().vel }))
await p.evaluate(() => window.__town3dCruise(true))
await p.waitForTimeout(2600)
const moving = await p.evaluate(() => ({ pr: window.__town3dStats().pr, vel: window.__town3dDbg().vel }))
console.log("HOVER(stopped overlook):", JSON.stringify(hover))
console.log("MOVING(fast):", JSON.stringify(moving))
await b.close()
