import { chromium } from "playwright"
const port = process.env.PORT || "4801"
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
await p.goto(`http://localhost:${port}/seasons-gpu/?dev=1`, { waitUntil: "networkidle" })
await p.locator(".gate").click().catch(()=>{})
await p.waitForTimeout(700)
await p.evaluate(() => window.__applyScene("kitaterao-window-3d"))
await p.waitForTimeout(2400)
await p.evaluate(() => { window.__town3dFly(true) })
await p.evaluate(() => { window.__town3dCruise(false) })
await p.evaluate(() => window.__town3dFlyPose(560, 34, -46, Math.PI/2, -0.12))
await p.waitForTimeout(800)
await p.screenshot({ path: "scripts/_shots/p2-edo.png" })
await p.evaluate(() => window.__town3dFlyPose(-588, 30, -30, -Math.PI/2, -0.1))
await p.waitForTimeout(800)
await p.screenshot({ path: "scripts/_shots/p2-taisho.png" })
await b.close()
