import { chromium } from "playwright"
const port = process.env.PORT || "4801"
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
await p.goto(`http://localhost:${port}/seasons-gpu/?dev=1`, { waitUntil: "networkidle" })
await p.locator(".gate").click().catch(()=>{})
await p.waitForTimeout(700)
await p.evaluate(() => window.__applyScene("kitaterao-window-3d"))
await p.waitForTimeout(2400)
await p.evaluate(() => { window.__town3dFly(true) })
await p.evaluate(() => { window.__town3dCruise(false) })
await p.evaluate(() => window.__town3dFlyPose(-150, 30, -85, 0, -0.2))
await p.waitForTimeout(900)
await p.screenshot({ path: "scripts/_shots/stadium-check.png" })
const h = await p.evaluate(() => { const f = []; for (const [dx,dz] of [[0,0],[0,-22],[0,22],[-22,0],[22,0]]) f.push(Math.round(window.__town3dHeightAt ? window.__town3dHeightAt(-150+dx,-116+dz) : 0)); return f })
console.log("stadium footprint heights [c,N,S,W,E]:", JSON.stringify(h))
await b.close()
