import { chromium } from 'playwright'
const port = process.env.PORT || '4801'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 720, height: 1280 }, deviceScaleFactor: 2 })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
await p.goto(`http://localhost:${port}/seasons-gpu/?dev=1`, { waitUntil: 'networkidle' })
await p.locator('.gate').click().catch(()=>{})
await p.waitForTimeout(800)
await p.evaluate(()=>window.__applyScene('kitaterao-window-3d-sunset'))
await p.waitForTimeout(3000)
console.log('toy at rest:', JSON.stringify(await p.evaluate(()=>window.__town3dToyPos())))
await p.evaluate(()=>window.__town3dCatBat()); await p.waitForTimeout(400)
console.log('toy after bat:', JSON.stringify(await p.evaluate(()=>window.__town3dToyPos())))
await p.screenshot({ path:'scripts/_shots/cat-toyroll.png', clip:{x:0,y:740,width:720,height:540} })
await p.waitForTimeout(3000)
console.log('toy settled:', JSON.stringify(await p.evaluate(()=>window.__town3dToyPos())))
console.log(errs.length?'ERR '+errs.slice(0,2):'no errors')
await b.close()
