// 視界を広げるモード: 飛行中に「広く」ボタンで広角＋引きになるか確認。
import { chromium } from 'playwright'
const port = process.env.PORT || '4801'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
page.on('pageerror', (e) => console.log('PAGE ERROR', e.message))
await page.goto(`http://localhost:${port}/seasons-gpu/?dev=1`, { waitUntil: 'networkidle' })
await page.locator('.gate').click().catch(() => {})
await page.waitForTimeout(700)
await page.evaluate(() => window.__applyScene('kitaterao-window-3d'))
await page.waitForTimeout(2400)
await page.evaluate(() => { window.__town3dWindow(true) }); await page.waitForTimeout(300)
await page.evaluate(() => { window.__town3dLean(true) }); await page.waitForTimeout(300)
await page.evaluate(() => { window.__town3dFly(true) }); await page.waitForTimeout(700)
await page.evaluate(() => { window.__town3dCruise(false) }); await page.waitForTimeout(150)
await page.evaluate(() => window.__town3dFlyPose(205, 30, -30, Math.PI / 2, -0.08)); await page.waitForTimeout(800)
const wideVisible = await page.evaluate(() => getComputedStyle(document.querySelector('.town3d-wide')).opacity)
console.log('wideボタン opacity(飛行中):', wideVisible)
await page.screenshot({ path: 'scripts/_shots/wide-off.png' })
await page.evaluate(() => document.querySelector('.town3d-wide__btn').dispatchEvent(new PointerEvent('pointerdown', { bubbles: true })))
await page.waitForTimeout(300)
console.log('wide active?', await page.evaluate(() => document.querySelector('.town3d-wide').classList.contains('wide--active')))
await page.evaluate(() => window.__town3dFlyPose(205, 30, -30, Math.PI / 2, -0.08)); await page.waitForTimeout(900)
await page.screenshot({ path: 'scripts/_shots/wide-on.png' })
console.log('wide shots done')
await browser.close()
