import { chromium } from 'playwright'
const browser = await chromium.launch()
const page = await browser.newPage({ viewport: { width: 440, height: 900 }, deviceScaleFactor: 2 })
await page.goto('http://localhost:4875/seasons/?dev=1', { waitUntil: 'networkidle' })
await page.evaluate(() => document.fonts.ready)
await page.locator('.gate').click().catch(() => {})
await page.waitForTimeout(600)
await page.addStyleTag({ content: '.ui{display:none !important}' })
await page.evaluate(() => window.__applyScene && window.__applyScene('shishigaya-window-3d-autumn'))
await page.waitForTimeout(2800)
await page.screenshot({ path: 'scripts/_shots/qa-yato2-front.png' })
// 身を乗り出して棚田を見下ろす
await page.evaluate(() => window.__town3dLean && window.__town3dLean(true))
await page.waitForTimeout(5200)
await page.evaluate(() => window.__town3dSetView && window.__town3dSetView(0, -0.7))
await page.waitForTimeout(900)
await page.screenshot({ path: 'scripts/_shots/qa-yato2-down.png' })
console.log('done')
await browser.close()
