import { chromium } from 'playwright'
const port = process.env.PORT || '4801'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 900, height: 600 }, deviceScaleFactor: 1.8 })
const errs=[]; p.on('pageerror',e=>errs.push(String(e)))
await p.goto(`http://localhost:${port}/seasons/?dev=1`, { waitUntil: 'networkidle' })
await p.locator('.gate').click().catch(()=>{})
await p.waitForTimeout(700)
await p.evaluate(()=>window.__applyScene('shishigaya-window-3d')); await p.waitForTimeout(2800)
await p.screenshot({ path:'scripts/_shots/yato-window.png' })
await p.evaluate(()=>window.__town3dFly(true)); await p.waitForTimeout(700)
await p.evaluate(()=>window.__town3dFlyPose(0,28,30,0,-0.4)); await p.waitForTimeout(1200)
await p.screenshot({ path:'scripts/_shots/yato-air.png' })
await p.evaluate(()=>window.__town3dFlyPose(0,4,8,0,-0.04)); await p.waitForTimeout(1200)
await p.screenshot({ path:'scripts/_shots/yato-low.png' })
console.log(errs.length?'ERR '+errs.slice(0,2):'no errors')
await b.close()
